// Code generated by "stringer -type=CITypeEnum"; DO NOT EDIT.

package structs

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[String-0]
	_ = x[MAC-1]
}

const _CITypeEnum_name = "StringMAC"

var _CITypeEnum_index = [...]uint8{0, 6, 9}

func (i CITypeEnum) String() string {
	if i < 0 || i >= CITypeEnum(len(_CITypeEnum_index)-1) {
		return "CITypeEnum(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CITypeEnum_name[_CITypeEnum_index[i]:_CITypeEnum_index[i+1]]
}
