// Code generated by "stringer -type=CITypeEnum"; DO NOT EDIT.

package structs

import "testing"

func TestCITypeEnum_String(t *testing.T) {
	tests := []struct {
		name string
		i    CITypeEnum
		want string
	}{
		{
			name: "String",
			i: String,
			want: "String",
		},
		{
			name: "MAC",
			i: MAC,
			want: "MAC",
		},
		{
			name: "Unknown",
			i: 2,
			want: "CITypeEnum(2)",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := tt.i.String(); got != tt.want {
				t.Errorf("CITypeEnum.String() = %v, want %v", got, tt.want)
			}
		})
	}
}
